### ISSUE TITLE
Getting Error while using "Start-IntuneBackup" command

### ISSUE THREAD

**Issue by gurpreet22** [jseerden/IntuneBackupAndRestore#14]
![image](https://user-images.githubusercontent.com/15626826/80675734-3ef7d680-8a83-11ea-841b-b1075e520633.png)

I have every module Installed. Is it some sort of bug?

**Comment by Arslan1196** [comment]
I  am getting the same error, it looks like the Microsoft must have change the command or there might be a different to try

**Comment by MietekW** [comment]
> 
> I have every module Installed. Is it some sort of bug?

Did you import the module?
import-module IntuneBackupAndRestore

do you see the module with get-module -listavailable ?

**Comment by gurpreet22** [comment]
I have the module.
See below image:
![image](https://user-images.githubusercontent.com/15626826/80805403-f248f400-8b85-11ea-9018-a7dddaa5a4a8.png)

**Comment by Arslannetworkhomes** [comment]
Same like him, I have got all the relevant modules installed

![image](https://user-images.githubusercontent.com/55056814/80988441-6f48c780-8e2b-11ea-9f7f-9949ae6bf74b.png)

**Comment by mikepgauthier** [comment]
Is it possible to correct the module to work with the new iteration of the graph?
Thanks.

I am receiving the same errors as the posters above.

**Comment by tehmichael** [comment]
Is this still an issue?

**Comment by jseerden** [comment]
Make sure to import the IntuneBackupAndRestore module with `Import-Module IntuneBackupAndRestore` before calling the Start-IntuneBackup cmdlet.
