### ISSUE TITLE
Can it be used to clone single policy?

### ISSUE THREAD

**Issue by SergGu** [jseerden/IntuneBackupAndRestore#20]
I'm using this tool to backup and compare Intune and it is great!

Since Microsoft does not have "clone" of the policy via native GUI (in devices > Configuration Policies), can this tool be used for creating cloned copy of the policies?
Note: cloning (e.g. Duplicate) is available in new Endpoint Security folder.

**Comment by jseerden** [comment]
Yes, you can create a backup (which exports current configuration to json files) and keep only the json files you want to duplicate. Then initiate a restore (it will create new policies next to the existing ones).
