### ISSUE TITLE
SettingsCatalog - Device configuration profile not backup

### ISSUE THREAD

**Issue by NextpointBelgium** [jseerden/IntuneBackupAndRestore#29]
Hi John,

First love your script to backup and restore endpoint manager configuration! 
Do you have any idea when you will update the PowerShell module so that settings catalog device configuration profiles will be included? Thank you in advance!

**Comment by nitram-rem** [comment]
Hi,

would it be possible to include also ESP and Deployment Profiles?

greetings

**Comment by RJLucas123** [comment]
Agreed.  We need this very badly!

**Comment by jseerden** [comment]
Hi @NextpointBelgium and @RJLucas123 ,

Session Catalog will be supported soon.

**Comment by NextpointBelgium** [comment]
Thanks for the effort John! :)

**Comment by NextpointBelgium** [comment]
> Hi @NextpointBelgium and @RJLucas123 ,
> 
> Session Catalog will be supported soon.

HI,

Any update on the script? thanks!

**Comment by jseerden** [comment]
Hi @NextpointBelgium , @RJLucas123 , version 3.0.0 of the IntuneBackupAndRestore PowerShell module now supports backup and restore actions for Settings Catalog!

**Comment by NextpointBelgium** [comment]
Cannot wait to test this out. Thanks you for your great effort! :)
