### ISSUE TITLE
Compare-IntuneBackupFile Depth Overflow

### ISSUE THREAD

**Issue by jonathan-ford** [jseerden/IntuneBackupAndRestore#31]
Hi jseerden,

I can see in version 2.1.1 you have addressed depth overflow issues. I get the below in version 2.0.0 and 2.1.1. 

PS C:\WINDOWS\system32> Compare-IntuneBackupFile -ReferenceFilePath "C:\FilePath\FileName2.json" -DifferenceFilePath "C:\FilePath\FileName1.json"
The script failed due to call depth overflow.
    + CategoryInfo          : InvalidOperation: (0:Int32) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CallDepthOverflow

Can you advise if this is a bug or user error.

**Comment by ztrhgf** [comment]
Solved in my pull request https://github.com/jseerden/IntuneBackupAndRestore/pull/44

**Comment by jseerden** [comment]
Verified fix #44. Pull request was merged
