### ISSUE TITLE
Compare-IntuneBackupDirectories - Cannot bind argument to parameter

### ISSUE THREAD

**Issue by jonathan-ford** [jseerden/IntuneBackupAndRestore#32]
Hi jseerden,

I'm getting the below error, can you advise if this is a bug or user error. 

PS C:\WINDOWS\system32> Compare-IntuneBackupDirectories -ReferenceDirectory "C:\IntuneConfig1" -DifferenceDirectory "C:\IntuneConfig2"         Compare-IntuneBackupFile : Cannot bind argument to parameter 'DifferenceFilePath' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\intunebackupandrestore\2.0.0\Public\Compare-IntuneBackupDirectories.ps1:62 char:94
+ ... ath $file.FileName -DifferenceFilePath $difFileFound.FullPath -ErrorA ...
+                                            ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-IntuneBackupFile], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Compare-IntuneBackupFile

Though I then also get results, so for each item it finds it seems to generate the same error above and then diff.

**Comment by jseerden** [comment]
Pull request was merged
