### ISSUE TITLE
Will there be support for Preview (setting catalog)

### ISSUE THREAD

**Issue by Johankapan** [jseerden/IntuneBackupAndRestore#34]
Not really an issue...Was hoping there would be support for the new settings catalog on the horizon.

**Comment by RJLucas123** [comment]
Agreed.  We need this very badly!

**Comment by jseerden** [comment]
Hi @Johankapan and @RJLucas123,

Session Catalog will be supported soon.

**Comment by jseerden** [comment]
Hi @Johankapan and @RJLucas123 , version 3.0.0 of the IntuneBackupAndRestore PowerShell module now supports backup and restore actions for Settings Catalog!
