### ISSUE TITLE
Unable to restore policies

### ISSUE THREAD

**Issue by SAYANKO** [jseerden/IntuneBackupAndRestore#35]
_Hello,
As long as the backup is working fine, I am not able to restore a policy.
Whenever I try to restore a single policy or more than one, I get the error "Error retrieving Intune Compliance Policy for C:\Temp\Device Compliance Policies\Assignments\DemoRecovery.json. Skipping assignment restore "
Remark: I get the same behavior for all types of policies that have been backed up.
I am using the modules:
Script 2.1.1 IntuneBackupAndRestore
Binary 6.1907.1.0 Microsoft.Graph.Intune

Has anyone had this problem as well?
Thank you_

**Comment by jseerden** [comment]
Hi @SAYANKO 

It seems you are trying to restore Assignments to policies that do not (yet) exist or have not been restored.

For example, when restoring Intune Compliance Policies and Assignments. Restore the Policies first, before restoring the Assignments.

For example: Run `Start-IntuneRestoreConfig` before `Start-IntuneRestoreAssignments`. Or run `Invoke-IntuneRestoreDeviceCompliancePolicy` before `Invoke-IntuneRestoreDeviceCompliancePolicyAssignment`

**Comment by SAYANKO** [comment]
__Hello,
Thank you for your reply.
I tired both, Start-IntuneRestoreConfig then Start-IntuneRestoreAssignments or running the dedicated invoke request. The json file is listed in the folder and as explained in the process I only kept one.
![image](https://user-images.githubusercontent.com/64503500/113490826-b2c40f80-949a-11eb-99ac-e4d4b8c2d782.png)
![image](https://user-images.githubusercontent.com/64503500/113490856-cec7b100-949a-11eb-9516-174a5905c7dd.png)

Thanks
