### ISSUE TITLE
Policies with brackets in their name cannot be saved

### ISSUE THREAD

**Issue by ErikvNoorden** [jseerden/IntuneBackupAndRestore#4]
Policies with brackets in their name (eg. '[ ]') result in errors by the backup scripts

example : 
Out-File : Cannot perform operation because the wildcard path C:\temp\export\Device Configurations\Assignments\[Test][Windows 10] Restriction - App Store.json did not resolve to a file.

using 'Out-File **-LiteralPath** ...' solves the problem

**Comment by jseerden** [comment]
Thanks for opening this issue. Will look into this. Also planning to fix backing up when there are characters in the Intune Configuration display names that are illegal in the filepath being saved to (`\/:*?"<>|`).

**Comment by jseerden** [comment]
This issue is fixed in the v1.3.0 release
