### ISSUE TITLE
Insufficient handling of multiple difference objects

### ISSUE THREAD

**Issue by ztrhgf** [jseerden/IntuneBackupAndRestore#45]
In case you have a file which is in multiple Assignments directories with the same name, using just parent folder name to filter out the right one isn't enough.

![image](https://user-images.githubusercontent.com/2930419/138047917-9bf2fd97-0de8-4857-9f4b-d84a403e2574.png)

SOLVED in https://github.com/jseerden/IntuneBackupAndRestore/pull/44/commits/c680f3549d8b217af54e19b4b9dd4d8504d15326

**Comment by jseerden** [comment]
Pull request was merged
