### ISSUE TITLE
Proactive remediations aren't backed up

### ISSUE THREAD

**Issue by ztrhgf** [jseerden/IntuneBackupAndRestore#46]
Proactive remediations https://endpoint.microsoft.com/#blade/Microsoft_Intune_Enrollment/UXAnalyticsMenu/proactiveRemediations aren't backed up

SOLVED in https://github.com/jseerden/IntuneBackupAndRestore/pull/44/commits/a0889122b4e4e5ad5d65221782a704e82e30d06e

**Comment by jseerden** [comment]
Pull request was merged
