### ISSUE TITLE
Compare-IntuneBackupFile error: The script failed due to call depth overflow.

### ISSUE THREAD

**Issue by ztrhgf** [jseerden/IntuneBackupAndRestore#47]
When using Compare-IntuneBackupFile, it fails on json files that contains hash in the property value.

Fixed in https://github.com/jseerden/IntuneBackupAndRestore/pull/44/commits/ebbc0e8e46aa9621ec834a3245328a77ce0f53e5

**Comment by jseerden** [comment]
Pull request was merged
