### ISSUE TITLE
IntuneBackupAndRestore v3.2.0 no Proactive Remediations scripts backuped

### ISSUE THREAD

**Issue by DM-Menno** [jseerden/IntuneBackupAndRestore#50]
First thanks for the great script!
I have upgraded to the latest version 3.2.0 but when I do a full backup I don't see any of the Proactive Remediations scripts in the backup folder.
Get-installedmodule is showing the following: 3.2.0 IntuneBackupAndRestore PSGallery
We have 13 remediations scripts some only detection and some detection and remediation, none are backuped.

Regards Menno

**Comment by jseerden** [comment]
Hi @DM-Menno ,

Do you see the "Device Health Scripts" folders in the Backup directory? This is how Microsoft Graph refers to Proactive Remediations. They should be in there.

**Comment by DM-Menno** [comment]
Hi @jseerden 

No it's not there

07-01-2022  10:53    <DIR>          Administrative Templates
07-01-2022  10:55    <DIR>          App Protection Policies
07-01-2022  10:51    <DIR>          Client Apps
07-01-2022  10:53    <DIR>          Device Compliance Policies
07-01-2022  10:53    <DIR>          Device Configurations
07-01-2022  10:55    <DIR>          Device Management Intents
07-01-2022  10:53    <DIR>          Device Management Scripts

**Comment by jseerden** [comment]
Hi @DM-Menno 

I'm unable to reproduce this issue. In my testing (with 3.2.0) Device Health Scripts are successfully backed up. Whether a remediation script is available or not.

 
![image](https://user-images.githubusercontent.com/20967759/148750729-1f852caf-12be-4cc9-8280-c6d595883044.png)

**Comment by DM-Menno** [comment]
I guess that I forgot to do the import after updating 

![image](https://user-images.githubusercontent.com/66735683/148754665-137ef62f-d160-4f81-8847-97a3807e0538.png)

Thanks for your support! issue can be closed
