### ISSUE TITLE
Any plans to add APP

### ISSUE THREAD

**Issue by PlanetWilson** [jseerden/IntuneBackupAndRestore#8]
App protection policies would be good to include, any plans around that?

**Comment by tehmichael** [comment]
There's a decent pull request from [sleeuwenhoek](https://github.com/jseerden/IntuneBackupAndRestore/pull/23) that includes app protection policies.  Downloading their version of the module seems to work quite nicely for this!

**Comment by jseerden** [comment]
Just updated the module to version 2.1.0, which includes app protection policies. Special thanks to @sleeuwenhoek
